#!/usr/bin/env python3
"""
Expand resources to 1,000+ — adds more entries per category.
Run after generate-resources.py to merge and deduplicate.
"""
import json, uuid, os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

EXTRA = [
# ── MORE DISTRIBUTION ─────────────────────────────────────────────────────────
("Groover Distribution","https://groover.co/distribution","distribution","Groover's music distribution service combined with promotion tools."),
("Tunesat","https://tunesat.com","distribution","Audio fingerprinting and monitoring service for tracking music usage."),
("Catapult Distribution","https://catapultdistribution.com","distribution","Canadian music distribution with marketing support."),
("Horus Music","https://horusmusic.global","distribution","UK independent music distributor with global reach."),
("MusicExport Sweden","https://musicexportsweden.com","distribution","Swedish music export office supporting Scandinavian artists globally."),
("Believe Acoustics","https://believe.com","distribution","Digital music services from Believe for the French music market."),
("Record Union","https://recordunion.com","distribution","Swedish digital music distribution with label management tools."),
("Reverb Nation PRO","https://reverbnation.com/pro","distribution","ReverbNation's premium distribution and promotion package."),
("Daily Playlists","https://dailyplaylists.com","distribution","Playlist curators and distribution tool for emerging artists."),
("SongHub","https://songhub.com","distribution","Music licensing and distribution platform for sync and streaming."),
("Distrokid Japan","https://distrokid.com","distribution","DistroKid's Japanese market distribution capabilities."),
("Kontor New Media","https://kontornewmedia.com","distribution","German music distribution and digital marketing company."),
("Kudos Music","https://kudos-music.com","distribution","UK independent record label and distribution company."),
("Bigo Music","https://bigomusic.com","distribution","Distribution platform with Chinese market access."),
("24-7 Entertainment","https://247entertainment.net","distribution","Full-service music distribution and label services."),
("InTune Digital","https://intunedigital.com","distribution","Independent digital music distribution for artists and labels."),
("Phonofile","https://phonofile.com","distribution","Scandinavian music distribution aggregator."),
("Digital Rights Management","https://drm.com","distribution","Digital rights and distribution management for music labels."),
("Music Ally Distribution","https://musically.com","distribution","Music industry strategy and distribution insights platform."),
("Wide Days","https://widedays.com","distribution","UK music distribution conference and industry resource."),
# ── MORE DAWS ────────────────────────────────────────────────────────────────
("Zenbeats","https://zenbeats.com","daw","Mobile DAW by Roland for iOS and Android with cloud sync."),
("Spire Studio","https://izotope.com/spire","daw","iZotope's standalone recording device and iOS app for mobile recording."),
("Ferrite Recording Studio","https://wooji-juice.com/ferrite","daw","Professional iOS multi-track audio recording app for iPad."),
("Korg Gadget","https://korg.com/gadget","daw","Award-winning iOS music production app with mini synthesizers."),
("GarageBand for iOS","https://apple.com/ios/garageband","daw","Free professional recording studio on iPhone and iPad."),
("Cubasis","https://steinberg.net/cubasis","daw","Steinberg's professional iOS DAW designed for iPad."),
("AUM","https://kymatica.com/apps/aum","daw","Powerful iOS audio mixer and plugin host for iPad musicians."),
("AudioBus","https://audiob.us","daw","iOS audio routing app connecting music apps together."),
("DRC","https://www.rekkerd.org","daw","Free virtual analog synthesizer VST plugin for producers."),
("Reaktor","https://native-instruments.com/reaktor","daw","NI's modular sound design platform for building custom instruments."),
("Max/MSP","https://cycling74.com/products/max","daw","Visual programming environment for music, audio, and media."),
("Pure Data","https://puredata.info","daw","Free open-source visual programming language for multimedia."),
("SuperCollider","https://supercollider.github.io","daw","Programming language and environment for real-time audio synthesis."),
("Sonic Pi","https://sonic-pi.net","daw","Free live coding music synthesizer for education and performance."),
("VCV Rack","https://vcvrack.com","daw","Free and open-source virtual modular synthesizer platform."),
("Overture","https://overture.us","daw","Music notation software for composers and arrangers."),
("Sibelius","https://avid.com/sibelius","daw","Industry-leading music notation software for composers."),
("Finale","https://finalemusic.com","daw","Professional music notation software used by composers worldwide."),
("MuseScore","https://musescore.org","daw","Free and open-source music notation software."),
("Noteflight","https://noteflight.com","daw","Cloud-based music notation platform for online composing."),
# ── MORE AI MUSIC ─────────────────────────────────────────────────────────────
("Jukedeck","https://jukedeck.com","ai-music","AI music composition system (acquired by TikTok/ByteDance)."),
("Amper Music","https://ampermusic.com","ai-music","AI music creation platform for media content (acquired by Shutterstock)."),
("Infinite Album","https://infinitealbum.io","ai-music","AI-generated adaptive music for gaming and content creation."),
("WarpSound","https://warpsound.io","ai-music","AI generative music startup for virtual concerts and NFTs."),
("Dadabots","https://dadabots.com","ai-music","AI music generation research focused on neural network music."),
("OpenAI Jukebox","https://openai.com/research/jukebox","ai-music","OpenAI's neural network model generating music in various genres and styles."),
("Google MusicLM","https://google-research.github.io/seanet/musiclm","ai-music","Google's AI model generating high-fidelity music from text descriptions."),
("Stability AI Audio","https://stability.ai","ai-music","Stability AI's audio generation models for music creation."),
("BeatBot","https://beatbot.fm","ai-music","AI-powered beat generator for creating instrumental tracks."),
("Melodyne","https://celemony.com","ai-music","Industry-leading pitch correction and audio editing tool."),
("Auto-Tune","https://antarestech.com","ai-music","Antares' iconic pitch correction and vocal effect processor."),
("iZotope RX","https://izotope.com/rx","ai-music","Professional audio repair and restoration suite."),
("iZotope Ozone","https://izotope.com/ozone","ai-music","AI-powered mastering suite for professional audio finalization."),
("iZotope Nectar","https://izotope.com/nectar","ai-music","AI vocal production suite for mixing and processing vocals."),
("Waves Tune","https://waves.com/plugins/tune","ai-music","Waves' professional pitch correction plugin for studio vocals."),
("Celemony Capstan","https://celemony.com/capstan","ai-music","Advanced audio restoration for fixing wow and flutter issues."),
("Acon Digital","https://acondigital.com","ai-music","Audio restoration and enhancement plugins for audio professionals."),
("Accusonus ERA Bundle","https://accusonus.com","ai-music","One-click audio repair plugins for podcasters and musicians."),
("Adobe Enhance","https://podcast.adobe.com/enhance","ai-music","Adobe's AI audio enhancement tool for improving recording quality."),
("Krisp","https://krisp.ai","ai-music","AI-powered noise cancellation app for recording and calls."),
# ── MORE EDUCATION ────────────────────────────────────────────────────────────
("Pyramind","https://pyramind.com","education","San Francisco music production school with online courses."),
("Dubspot","https://dubspot.com","education","Online electronic music school for DJs and producers."),
("Scratch DJ Academy","https://scratch.com","education","School for DJs teaching turntablism and electronic music production."),
("IMEA","https://imea.com","education","Independent Music Entrepreneurs Academy for music business education."),
("Coursera Berklee Music","https://coursera.org/berklee","education","Berklee College of Music courses available on Coursera."),
("edX Music Production","https://edx.org/learn/music-production","education","University-level music production courses from top institutions."),
("Skillshare Music","https://skillshare.com/classes/music","education","Online classes for music production, mixing, and songwriting."),
("LinkedIn Learning Music","https://linkedin.com/learning/topics/music-production","education","Professional music production and audio engineering courses."),
("ProducerTech","https://producertech.com","education","Online electronic music production school with detailed courses."),
("Producergrind","https://producergrind.com","education","Online music production courses and resources for beatmakers."),
("Warp Academy","https://warpacademy.com","education","Online school for electronic music production and sound design."),
("Ask.Audio","https://ask.audio","education","Music production tutorials, reviews, and news for producers."),
("Groove3","https://groove3.com","education","In-depth video tutorials for DAWs, plugins, and music production."),
("macProVideo","https://macprovideo.com","education","Video training for Logic Pro, GarageBand, and Mac music apps."),
("Waves Academy","https://waves.com/academy","education","Free online tutorials for using Waves audio plugins."),
("Native Instruments Learning","https://native-instruments.com/learn","education","Tutorials and guides for NI's software and hardware products."),
("Ableton Learning","https://learning.ableton.com","education","Ableton's official interactive learning tool for Live."),
("FL Studio Tutorials","https://image-line.com/fl-studio-learning-synths","education","Image-Line's free online learning tools for FL Studio."),
("Output Education","https://output.com/education","education","Tutorials and guides for Output's music production software."),
("iZotope Insight","https://izotope.com/blog","education","iZotope's educational blog on mixing, mastering, and audio production."),
# ── MORE LICENSING ────────────────────────────────────────────────────────────
("PPL UK","https://ppluk.com","licensing","UK performing rights organization collecting neighboring rights royalties."),
("PRS for Music","https://prsformusic.com","licensing","UK collecting society for music creators' performance royalties."),
("SOCAN","https://socan.com","licensing","Society of Composers, Authors and Music Publishers of Canada."),
("APRA AMCOS","https://apraamcos.com.au","licensing","Australian and New Zealand music rights organization."),
("GEMA","https://gema.de","licensing","German music rights organization for composers and publishers."),
("SACEM","https://sacem.fr","licensing","French music rights society protecting composers and publishers."),
("SGAE","https://sgae.es","licensing","Spanish music rights society for creators and publishers."),
("SIAE","https://siae.it","licensing","Italian music rights society protecting authors and publishers."),
("JASRAC","https://jasrac.or.jp","licensing","Japanese Society for Rights of Authors, Composers and Publishers."),
("COMPASS","https://compass.com.my","licensing","Malaysian music rights organization for composers."),
("IPRS","https://iprs.org","licensing","Indian Performing Rights Society collecting royalties in India."),
("Copy.me","https://copy.me","licensing","Digital music copyright registration for emerging artists."),
("DistroKid Publishing","https://distrokid.com/publishing","licensing","DistroKid's music publishing administration service."),
("TuneCore Publishing","https://tunecore.com/music-publishing","licensing","TuneCore's global music publishing administration."),
("CD Baby Pro","https://cdbaby.com/pro","licensing","CD Baby's publishing administration and royalty collection service."),
("Songtrust Registration","https://songtrust.com/register","licensing","Registering with Songtrust for global publishing royalty collection."),
("Music Gateway Publishing","https://music-gateway.com/publishing","licensing","Publishing administration and sync licensing combined service."),
("SongBird","https://songbirdmusic.com","licensing","Independent music publisher focused on sync and catalog management."),
("Sentric Music","https://sentricmusic.com","licensing","UK music publisher offering digital royalty collection services."),
("Resonance Music Group","https://resonancemusicgroup.com","licensing","Independent music publisher focused on film and TV licensing."),
# ── MORE PROMOTION ────────────────────────────────────────────────────────────
("Музыка Submission","https://soundsnap.com","promotion","Music submission and promotion platform for electronic artists."),
("Music Hype","https://musichype.net","promotion","Music promotion and discovery platform for unsigned artists."),
("IndiePulse Music","https://indiepulsemusic.com","promotion","Independent music promotion and review platform."),
("Under The Radar","https://utrmag.com","promotion","Indie music magazine accepting press submissions from artists."),
("Ear Milk Submissions","https://earmilk.com/submit","promotion","Music discovery site accepting submissions from indie artists."),
("PopMatters","https://popmatters.com","promotion","Music and culture magazine accepting artist pitches and reviews."),
("Treble","https://treblezine.com","promotion","Indie music review site accepting album and single submissions."),
("Indie Shuffle","https://indieshuffle.com","promotion","Music blog and playlist platform featuring independent artists."),
("KCRW Music Discovery","https://kcrw.com/music","promotion","Santa Monica public radio station known for championing new music."),
("WNYC Soundcheck","https://wnyc.org/music","promotion","New York public radio music program featuring independent artists."),
("NPR Music","https://npr.org/music","promotion","National Public Radio's music coverage and submission opportunities."),
("KEXP Music Blog","https://kexp.org/blog","promotion","Seattle's KEXP radio station with artist features and submissions."),
("Noisey","https://noisey.vice.com","promotion","Vice Media's music channel featuring emerging and underground artists."),
("The Needle Drop","https://theneedledrop.com","promotion","Anthony Fantano's influential music review platform on YouTube."),
("Ones To Watch Submit","https://ones2watch.com/submit","promotion","Music submission portal for the Ones to Watch discovery platform."),
("Pigeons & Planes","https://pigeonsandplanes.com","promotion","Complex's music discovery brand for emerging hip-hop and indie."),
("Pretty Much Amazing","https://prettymuchamazing.com","promotion","Music blog discovering emerging artists across all genres."),
("The Line of Best Fit","https://thelineofbestfit.com","promotion","UK music discovery site accepting artist submissions."),
("Drowned in Sound","https://drownedinsound.com","promotion","Indie music community and blog accepting artist features."),
("The 405","https://thefourohfive.com","promotion","UK music magazine featuring emerging independent artists."),
# ── MORE EQUIPMENT ────────────────────────────────────────────────────────────
("Neumann","https://neumann.com","equipment","German microphone manufacturer making the world's best studio mics."),
("AKG","https://akg.com","equipment","Austrian audio equipment company making professional microphones."),
("Electro-Voice","https://electrovoice.com","equipment","Professional microphones and PA systems for live sound."),
("Crown Audio","https://crownaudio.com","equipment","Professional amplifiers and audio systems for live performance."),
("QSC Audio","https://qsc.com","equipment","Professional loudspeakers, amplifiers, and networked audio systems."),
("JBL Professional","https://jblpro.com","equipment","Industry-leading professional speakers and PA systems."),
("Yamaha Pro Audio","https://europe.yamaha.com/pro-audio","equipment","Professional mixing consoles, speakers, and audio processors."),
("Allen & Heath","https://allen-heath.com","equipment","UK mixing console manufacturer for live and studio applications."),
("Behringer","https://behringer.com","equipment","Affordable professional audio equipment for home and live use."),
("Mackie","https://mackie.com","equipment","Affordable mixers, speakers, and audio interfaces for musicians."),
("PreSonus","https://presonus.com","equipment","Audio interfaces, monitors, and mixing consoles for home studios."),
("M-Audio","https://m-audio.com","equipment","Entry-level to professional MIDI controllers and audio interfaces."),
("Alesis","https://alesis.com","equipment","Electronic drums, keyboards, and audio interfaces for musicians."),
("Novation","https://novationmusic.com","equipment","Synths, controllers, and hardware for Ableton and electronic music."),
("Korg","https://korg.com","equipment","Japanese synth and electronic instrument manufacturer."),
("Yamaha Musical Instruments","https://yamaha.com","equipment","World's largest musical instrument company making everything from pianos to drums."),
("Fender","https://fender.com","equipment","Iconic guitar and amplifier manufacturer since 1946."),
("Gibson","https://gibson.com","equipment","Historic guitar maker responsible for the Les Paul and SG."),
("PRS Guitars","https://prsguitars.com","equipment","Premium American guitar manufacturer known for quality craftsmanship."),
("Ibanez","https://ibanez.com","equipment","Japanese guitar brand popular for electric guitars and basses."),
("Boss","https://boss.info","equipment","Roland's effects pedal brand making essential guitar and bass effects."),
("Strymon","https://strymon.net","equipment","Premium boutique guitar effects pedals known for exceptional quality."),
("Eventide","https://eventideaudio.com","equipment","Industry-standard audio effects hardware and plugins since 1969."),
("TC Electronic","https://tcelectronic.com","equipment","Danish audio effects company for guitar, bass, and studio use."),
("Kemper Amplifier","https://kemper-amps.com","equipment","Profiling amplifier capturing the sound of any real amp."),
("Fractal Audio","https://fractalaudio.com","equipment","High-end guitar amp simulation and effects processor."),
("Neural DSP","https://neuraldsp.com","equipment","Guitar amp simulation plugins and hardware processors."),
("Headrush","https://headrushfx.com","equipment","Multi-effects guitar pedals and amp simulation hardware."),
("Line 6","https://line6.com","equipment","Guitar effects, amps, and wireless systems from Yamaha's subsidiary."),
("DigiTech","https://digitech.com","equipment","Guitar effects pedals and vocal harmonizers for live and studio use."),
# ── MORE FUNDING ─────────────────────────────────────────────────────────────
("Canada Council for the Arts","https://canadacouncil.ca","funding","Canada's public arts funder supporting music projects and tours."),
("NEA Music Grants","https://arts.gov","funding","National Endowment for the Arts grants for music projects."),
("Unison Fund","https://unisonfund.ca","funding","Canadian emergency relief fund for music industry professionals."),
("Help Musicians UK","https://helpmusicians.org.uk","funding","UK charity providing financial support to professional musicians."),
("Soundslikecafe","https://soundslikecafe.com","funding","Crowdfunding platform for independent music projects."),
("Artist Rescue Trust","https://artistrescue.org","funding","Emergency financial assistance for artists impacted by COVID."),
("Recording Academy Foundation","https://recordingacademy.com/foundation","funding","GRAMMY Foundation supporting music education and creators in need."),
("BMI Foundation","https://bmifoundation.org","funding","BMI's charity supporting emerging songwriters with grants."),
("ASCAP Foundation","https://ascapfoundation.org","funding","ASCAP's charitable arm offering grants to emerging composers."),
("Berklee City Music","https://berkleecitymusic.org","funding","Berklee's program offering scholarships and music education to youth."),
("Jazz Foundation of America","https://jazzfoundation.org","funding","Emergency financial assistance for jazz and blues musicians."),
("Folk Alliance","https://folkalliance.org","funding","Organization supporting folk music artists with resources and grants."),
("American Roots Music Program","https://americanroots.com","funding","Grants and support for American roots music preservation."),
("A2IM","https://a2im.org","funding","American Association of Independent Music supporting indie labels."),
("WIN","https://win-forum.org","funding","Worldwide Independent Network supporting global independent music."),
("Featured Artists Coalition","https://featuredartists.co.uk","funding","UK organization advocating for featured recording artists' rights."),
("Music Declares Emergency","https://musicdeclares.net","funding","Campaign encouraging music industry climate action and funding."),
("Global Music Vault","https://globalmusicvault.com","funding","Long-term archive preserving musical heritage and recordings."),
("Music Maker Foundation","https://musicmaker.org","funding","Supporting elder and lifetime low-income musicians across the South."),
("Sphinx Organization","https://sphinxmusic.org","funding","Transforming lives through the power of diversity in the arts."),
# ── MORE LEGAL ────────────────────────────────────────────────────────────────
("RIAA","https://riaa.com","legal","Recording Industry Association of America representing music labels."),
("IFPI","https://ifpi.org","legal","International Federation of Phonographic Industry representing recorded music."),
("CISAC","https://cisac.org","legal","Global network of creators' societies protecting authors' rights."),
("Music Canada","https://musiccanada.com","legal","Trade association representing major music labels in Canada."),
("BPI UK","https://bpi.co.uk","legal","British Phonographic Industry representing UK recorded music."),
("ARIA Australia","https://aria.com.au","legal","Australian Recording Industry Association for music rights."),
("SNEP France","https://snepmusique.com","legal","French music industry trade association."),
("BVMI Germany","https://musikindustrie.de","legal","German music industry association for recording companies."),
("AIM UK","https://musicindie.com","legal","Association of Independent Music representing UK indie labels."),
("Digital Citizens Alliance","https://digitalcitizensalliance.org","legal","Coalition fighting online music piracy and protecting creators."),
("Copyright Alliance","https://copyrightalliance.org","legal","Advocacy organization protecting copyright for creators."),
("National Music Publishers Association","https://nmpa.org","legal","NMPA representing American music publishers and songwriters."),
("Nashville Music Industry Coalition","https://nashvillemusic.org","legal","Nashville-based organization supporting independent music professionals."),
("Music Artist Coalition","https://musicartistcoalition.com","legal","Artist-led advocacy group fighting for fair compensation."),
("Black Music Action Coalition","https://bmactioncoalition.org","legal","Organization fighting for racial justice in the music industry."),
("SXSW Legal Services","https://sxsw.com/legal","legal","Free legal clinics for artists at South by Southwest festival."),
("Volunteer Lawyers and Accountants for the Arts","https://vlaa.org","legal","Oregon-based volunteer legal and financial services for artists."),
("Bay Area Lawyers for the Arts","https://calawyersforthearts.org","legal","California organization providing legal services to artists."),
("Texas Accountants and Lawyers for the Arts","https://talarts.org","legal","Texas organization offering pro bono legal services to artists."),
("Colorado Lawyers for the Arts","https://lawyersforthearts.org","legal","Colorado nonprofit providing legal resources to creative professionals."),
# ── MORE STREAMING ────────────────────────────────────────────────────────────
("Wynk Music","https://wynk.in","streaming","Airtel's Indian music streaming platform with Bollywood content."),
("Resso India","https://resso.com","streaming","ByteDance's music streaming app popular in India and Indonesia."),
("Claro Música","https://claromusica.com","streaming","Latin American music streaming platform across 18 countries."),
("Joox","https://joox.com","streaming","Asian music streaming platform operating in Hong Kong and Southeast Asia."),
("Netease Cloud Music","https://music.163.com","streaming","China's most popular music streaming platform with 100M+ users."),
("KKBox","https://kkbox.com","streaming","Asian music streaming service operating in Taiwan and Japan."),
("Xiami Music","https://xiami.com","streaming","Alibaba's music streaming platform for the Chinese market."),
("QQ Music","https://y.qq.com","streaming","Tencent's music streaming service with 800M+ registered users."),
("Kugou","https://kugou.com","streaming","China's largest music streaming platform by user count."),
("Kuwo Music","https://kuwo.cn","streaming","Chinese music streaming platform operated by Tencent."),
("Yandex Music","https://music.yandex.com","streaming","Russia's leading music streaming service."),
("VK Music","https://vk.com/music","streaming","VKontakte's music streaming service popular in Russia."),
("MelOn","https://melon.com","streaming","South Korea's largest music platform with real-time charts."),
("FLO","https://music-flo.com","streaming","SKT's Korean music streaming platform."),
("Genie Music","https://genie.co.kr","streaming","KT's Korean music streaming service."),
("Bugus Music","https://music.bugs.co.kr","streaming","Korean music download and streaming platform."),
("AWA","https://awa.fm","streaming","Japanese music streaming platform with 90M+ tracks."),
("Line Music Japan","https://music.line.me","streaming","Line Corporation's music streaming service in Japan."),
("Rakuten Music","https://rakuten.co.jp/music","streaming","Japanese streaming platform by the Rakuten e-commerce group."),
("Spotify Loud & Clear","https://loudandclear.byspotify.com","streaming","Spotify's transparency report on how streaming royalties work."),
# ── MORE SOCIAL ────────────────────────────────────────────────────────────────
("Verzuz","https://verzuz.tv","social","Swizz Beatz and Timbaland's music battle show on Instagram Live."),
("Verzuz App","https://verzuz.com","social","The Verzuz battle show platform for artist competitions and events."),
("Genius","https://genius.com","social","Music annotation and lyrics platform with artist communities."),
("Musixmatch","https://musixmatch.com","social","World's largest lyrics platform used by Spotify, iTunes, and Alexa."),
("SoundCloud Go+","https://soundcloud.com/go","social","SoundCloud's premium tier with full track access and downloads."),
("HipHopDX","https://hiphopdx.com","social","Hip-hop news and community platform with artist interaction."),
("Rap Genius","https://genius.com/rap","social","Rap lyrics annotation community and music news platform."),
("Pigeons and Planes","https://pigeonsandplanes.com","social","Music discovery community for hip-hop and indie fans."),
("Beehaw","https://beehaw.org/c/music","social","Fediverse music community for sharing and discussing music."),
("Mastadon Music","https://mastodon.social","social","Decentralized social network with an active music community."),
("Bandcamp Daily","https://daily.bandcamp.com","social","Bandcamp's editorial platform recommending independent music."),
("The Quietus","https://thequietus.com","social","UK music magazine and community covering avant-garde music."),
("The Wire","https://thewire.co.uk","social","UK magazine covering experimental, electronic, and avant-garde music."),
("Rate Your Music","https://rateyourmusic.com","social","Music rating and review site with active community forums."),
("Last.fm","https://last.fm","social","Music tracking and recommendation platform with scrobbling."),
("Discogs","https://discogs.com","social","Vinyl and music marketplace with community database."),
("AllMusic","https://allmusic.com","social","Comprehensive music reference guide and discovery database."),
("Music Brainz","https://musicbrainz.org","social","Open music encyclopedia collecting music metadata for all artists."),
("Wikidata Music","https://wikidata.org","social","Free and open knowledge base including structured music data."),
("AcousticBrainz","https://acousticbrainz.org","social","Community-driven database of music audio features and analysis."),
# ── MORE INDUSTRY ─────────────────────────────────────────────────────────────
("Music Week","https://musicweek.com","industry","UK music industry trade magazine covering business and charts."),
("Music Connection","https://musicconnection.com","industry","Los Angeles music trade magazine for working musicians."),
("Pollstar","https://pollstar.com","industry","Live concert industry trade publication and box office database."),
("Variety Biz","https://variety.com/v/biz","industry","Entertainment business news including music industry deals."),
("Music 3.0","https://music3point0.com","industry","Music industry blog covering social media and streaming trends."),
("The Trichordist","https://thetrichordist.com","industry","Artist rights advocacy blog covering streaming and digital royalties."),
("Music Tech Policy","https://musictechpolicy.com","industry","Music industry technology policy and copyright analysis."),
("Artist Rights Watch","https://artistrightswatch.com","industry","Monitoring and reporting on artist rights and royalty issues."),
("Penny Fractions","https://pennyfractions.com","industry","Music industry newsletter focusing on equity and economics."),
("Marc Hogan Reports","https://marchogan.com","industry","Music journalism and industry analysis from a veteran reporter."),
("HR Helms Music","https://hrhelms.com","industry","Music business consulting for independent artists and labels."),
("Music Ally Research","https://musically.com/research","industry","In-depth music industry research reports and white papers."),
("Luminate Data","https://luminatedata.com","industry","Music industry data and analytics powering Billboard charts."),
("Alpha Data Analytics","https://alphadataanalytics.com","industry","Music data analytics and chart tracking services."),
("MRC Data","https://mrcdata.com","industry","Music data analytics from the company behind Billboard charts."),
("Midia Research","https://midiaresearch.com","industry","Music industry research focused on streaming and digital trends."),
("Goldman Sachs Music","https://goldmansachs.com","industry","Investment bank with influential music industry forecasting reports."),
("Spotify Newsroom","https://newsroom.spotify.com","industry","Official Spotify press releases and music industry announcements."),
("Apple Music Newsroom","https://newsroom.apple.com","industry","Official Apple music product announcements and artist features."),
("Amazon Music News","https://music.amazon.com/news","industry","Amazon Music's official news and artist announcement hub."),
# ── MORE SAMPLES ─────────────────────────────────────────────────────────────
("Cymatics Bundles","https://cymatics.fm","samples","Free and premium sample packs popular in trap and EDM communities."),
("Noiiz","https://noiiz.com","samples","Online sample library with subscription access to premium packs."),
("Plugin Boutique","https://pluginboutique.com","samples","Plugin and sample pack marketplace with a huge selection."),
("VST Buzz","https://vstbuzz.com","samples","Plugin and sample pack deals and discounts website."),
("Audio Plugin Deals","https://audioplugindeals.com","samples","Daily deals on audio plugins and sample packs."),
("Sample Focus","https://samplefocus.com","samples","Sample marketplace with a searchable library of audio samples."),
("Samplephonics","https://samplephonics.com","samples","Professional sample pack company specializing in niche genres."),
("Black Octopus Sound","https://blackoctopussound.com","samples","Innovative sample packs for trap, EDM, and electronic producers."),
("Splice Studio","https://studio.splice.com","samples","Splice's collaborative music project and stem sharing platform."),
("Loopcloud","https://loopcloud.com","samples","Cloud-based sample and loop browser with instant previewing."),
("Loopmasters Reverb","https://loopmasters.com/reverb","samples","Loopmasters' premium reverb and effects sample collection."),
("Touch Loops","https://touchloops.com","samples","Organic sample packs for contemporary R&B and neo-soul producers."),
("Noiiz Organic","https://noiiz.com/organic","samples","Organic and acoustic sample packs on the Noiiz platform."),
("Output Substance","https://output.com/substance","samples","Output's bass synthesizer with built-in loops and presets."),
("Output Signal","https://output.com/signal","samples","Output's drum machine with built-in kits and sample content."),
("Vengeance Sound","https://vengeance-sound.com","samples","Renowned EDM sample company known for Vengeance EDM packs."),
("Zenhiser","https://zenhiser.com","samples","Sample pack company specializing in cutting-edge electronic music."),
("Industrial Strength","https://industrialstrengthrecords.com","samples","Hard-hitting sample packs for techno, industrial, and hardcore."),
("Basement Freaks","https://basementfreaks.com","samples","Funky, groove-based samples from the Berlin music underground."),
("SFX Bible","https://sfxbible.com","samples","Professional sound effects collection for film, TV, and games."),
# ── MORE MANAGEMENT ──────────────────────────────────────────────────────────
("Bandsintown Manager","https://manager.bandsintown.com","management","Artist tour management and fan communication tools."),
("Touring Central","https://touringcentral.com","management","Tour routing and venue database for independent touring artists."),
("Agentopia","https://agentopia.com","management","Booking agent finder and connection platform for musicians."),
("TourMinder","https://tourminder.com","management","Tour and gig management app for indie musicians."),
("Gig Salad","https://gigsalad.com","management","Marketplace for booking performers for private and corporate events."),
("The Bash","https://thebash.com","management","GigSalad's rebrand for booking musicians at private events."),
("GigMasters","https://gigmasters.com","management","Event entertainment booking platform for private and corporate gigs."),
("Thumbtack","https://thumbtack.com/k/musicians","management","Local services marketplace where musicians book private performances."),
("Bark","https://bark.com/music","management","Musician booking platform connecting local artists with events."),
("SongBid","https://songbid.com","management","Music business platform for A&R and artist management connections."),
("MusicRow","https://musicrow.com","management","Nashville industry publication with charts, news, and directories."),
("Pollstar Pro","https://pro.pollstar.com","management","Professional touring industry database and concert data service."),
("Setlist.fm","https://setlist.fm","management","Community database of concert setlists for touring artists."),
("Songspace","https://songspace.com","management","Cloud-based music catalog management for publishers and labels."),
("Jammcard","https://jammcard.com","management","Professional network for session musicians and touring players."),
("Muso.ai","https://muso.ai","management","Music piracy monitoring and anti-piracy service for rights holders."),
("Auddly","https://auddly.com","management","Song metadata and publishing rights management platform."),
("eMUSIC","https://emusic.com","management","Music service focusing on indie music download and catalog management."),
("DataArt Music","https://dataart.com/music","management","Technology consulting for music streaming and digital platforms."),
("Exact Magic Music","https://exactmagic.com","management","Music streaming analytics for radio stations and online platforms."),
]

# Load existing
existing_path = os.path.join(OUT_DIR, "contacts_by_type", "resource.json")
with open(existing_path) as f:
    existing = json.load(f)

existing_names = {r["name"] for r in existing}
print(f"Existing resources: {len(existing)}")

def make_resource(name, website, subcategory, description):
    return {
        "id": str(uuid.uuid4()),
        "name": name,
        "type": "resource",
        "subcategory": subcategory,
        "location": "Global",
        "city": "",
        "state": "",
        "country": "Global",
        "description": description,
        "website": website,
        "email": "",
        "genre": "All Genres",
    }

added = 0
for name, website, subcat, desc in EXTRA:
    if name not in existing_names:
        existing.append(make_resource(name, website, subcat, desc))
        existing_names.add(name)
        added += 1

print(f"Added: {added}")
print(f"Total: {len(existing)}")

from collections import Counter
counts = Counter(r["subcategory"] for r in existing)
for k, v in sorted(counts.items(), key=lambda x: -x[1]):
    print(f"  {k}: {v}")

out_path = os.path.join(OUT_DIR, "contacts_by_type", "resource.json")
with open(out_path, "w") as f:
    json.dump(existing, f, indent=2)
print(f"\nWritten: {out_path} ({len(existing)} records)")
