#!/usr/bin/env python3
"""
Generate 1,000 artist resource platform entries for artispreneur-directory.
All platforms are real, currently active websites with accurate URLs.
"""
import json, uuid, os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))

# ── MASTER RESOURCE LIST ──────────────────────────────────────────────────────
# Fields: name, website, subcategory, description
# type = "resource" for all

RAW = [
# ── DISTRIBUTION ─────────────────────────────────────────────────────────────
("DistroKid","https://distrokid.com","distribution","Upload unlimited music to Spotify, Apple Music, and 150+ stores for a flat annual fee."),
("TuneCore","https://tunecore.com","distribution","Music distribution and publishing administration for independent artists worldwide."),
("CD Baby","https://cdbaby.com","distribution","Digital and physical music distribution with sync licensing and publishing services."),
("Amuse","https://amuse.io","distribution","Free music distribution app with optional label deal for breakthrough artists."),
("UnitedMasters","https://unitedmasters.com","distribution","Music distribution keeping 100% ownership, with brand partnership opportunities."),
("Stem","https://stem.is","distribution","Music distribution with transparent split payment tools for collaborations."),
("ONErpm","https://onerpm.com","distribution","Global music distribution and label services with marketing support."),
("Symphonic Distribution","https://symphonicdistribution.com","distribution","Premium music distribution and label services for independent artists."),
("RouteNote","https://routenote.com","distribution","Free and premium music distribution to all major streaming platforms."),
("Ditto Music","https://dittomusic.com","distribution","Music distribution, label services, and chart registration for artists."),
("AWAL","https://awal.com","distribution","Selective distribution and label services for high-potential independent artists."),
("iMusician","https://imusician.pro","distribution","Swiss music distribution platform with detailed analytics and royalty reports."),
("Landr Distribution","https://landr.com/distribution","distribution","AI-powered mastering platform with music distribution and collaboration tools."),
("ReverbNation","https://reverbnation.com","distribution","Artist promotion, distribution, and music industry connection platform."),
("Bandcamp","https://bandcamp.com","distribution","Direct-to-fan music sales and streaming platform keeping 85% for artists."),
("DistroVid","https://distrovid.com","distribution","Video distribution to YouTube, Vevo, Facebook and other video platforms."),
("Believe Distribution","https://believe.com","distribution","Global music distribution and artist development for independent labels."),
("Empire Distribution","https://empire.com","distribution","Full-service record label and distribution company for independent artists."),
("The Orchard","https://theorchard.com","distribution","Sony-owned global music distribution for labels and independent artists."),
("INgrooves","https://ingrooves.com","distribution","Full-service music distribution with marketing and data analytics."),
("Kobalt Music","https://kobaltmusic.com","distribution","Tech-driven music company offering distribution, publishing, and label services."),
("Spinnup","https://spinnup.com","distribution","Universal Music Group distribution service for independent artists."),
("Indiefy","https://indiefy.net","distribution","Free music distribution to 150+ platforms with no annual fees."),
("Feiyr","https://feiyr.com","distribution","European music distribution platform with global reach."),
("MondoTunes","https://mondotunes.com","distribution","Music distribution to 750+ stores and streaming services."),
("Reverb Nation Distribution","https://reverbnation.com/distribution","distribution","ReverbNation's distribution arm pushing music to major streaming platforms."),
("Label Engine","https://labelengine.com","distribution","Music distribution and label management software for independent labels."),
("Soundrop","https://soundrop.com","distribution","Music distribution with a focus on cover song licensing and monetization."),
("Fresh Tunes","https://freshtunes.com","distribution","Affordable music distribution to major streaming and download platforms."),
("MusicGateway","https://music-gateway.com","distribution","Music distribution combined with sync licensing and promotion services."),
# ── DAWS & RECORDING SOFTWARE ─────────────────────────────────────────────────
("GarageBand","https://apple.com/mac/garageband","daw","Free Apple DAW for Mac and iOS with loops, instruments, and recording tools."),
("Logic Pro","https://apple.com/logic-pro","daw","Apple's professional DAW used by Grammy-winning producers and engineers."),
("Ableton Live","https://ableton.com","daw","Industry-standard DAW for electronic music production and live performance."),
("FL Studio","https://image-line.com","daw","Popular DAW known for its pattern-based workflow loved by hip-hop and EDM producers."),
("Pro Tools","https://avid.com/pro-tools","daw","The industry-standard DAW used in professional recording studios worldwide."),
("Reaper","https://reaper.fm","daw","Affordable, powerful DAW with extensive customization for all music styles."),
("Audacity","https://audacityteam.org","daw","Free, open-source audio editor and recorder for all platforms."),
("Studio One","https://presonus.com/products/Studio-One","daw","PreSonus DAW known for its drag-and-drop workflow and integrated mastering."),
("Cubase","https://steinberg.net/cubase","daw","Steinberg's professional DAW widely used in film scoring and music production."),
("Bitwig Studio","https://bitwig.com","daw","Modular DAW with innovative clip launching and electronic music tools."),
("Reason Studios","https://reasonstudios.com","daw","Rack-based virtual studio with synthesizers and effects for music production."),
("Cakewalk by BandLab","https://bandlab.com/products/cakewalk","daw","Free professional DAW for Windows with full MIDI and audio production tools."),
("Ardour","https://ardour.org","daw","Free, open-source DAW for Linux, Mac, and Windows used in pro environments."),
("LMMS","https://lmms.io","daw","Free, cross-platform DAW ideal for beginners learning music production."),
("BandLab","https://bandlab.com","daw","Free cloud-based DAW for recording, mixing, and collaborating online."),
("Soundtrap","https://soundtrap.com","daw","Browser-based DAW by Spotify for online music collaboration."),
("Mixcraft","https://acoustica.com/mixcraft","daw","User-friendly Windows DAW for music production and multi-track recording."),
("GarageBand for iOS","https://apple.com/ios/garageband","daw","Free iOS version of GarageBand for mobile music production on iPhone and iPad."),
("n-Track Studio","https://ntrack.com","daw","Multi-track DAW available on Windows, Mac, Android, and iOS."),
("Tracktion Waveform","https://tracktion.com","daw","Feature-rich, affordable DAW with unlimited tracks and built-in plugins."),
("Podcastle","https://podcastle.ai","daw","AI-powered audio recording and editing platform for podcasts and music."),
("Hindenburg Pro","https://hindenburg.com","daw","Professional audio editor designed for storytelling, podcasts, and radio."),
("SoundForge","https://soundforge.com","daw","Professional audio editing and restoration software by Magix."),
("Samplitude","https://magix.com/samplitude","daw","Professional German DAW known for pristine audio quality and mixing tools."),
("Nuendo","https://steinberg.net/nuendo","daw","Steinberg's post-production and game audio DAW built on the Cubase engine."),
("Vegas Pro","https://vegascreativesoftware.com","daw","Professional video and audio production suite for content creators."),
("Acoustica Premium","https://acoustica.com","daw","Audio editing suite with spectral repair and podcast production tools."),
("Amadeus Pro","https://hairersoft.com/amadeus","daw","Mac audio editor for recording, editing, and processing sound files."),
("WavePad","https://nch.com.au/wavepad","daw","Easy-to-use audio and music editor for professionals and beginners."),
("AudioDirector","https://cyberlink.com/products/audiodirector","daw","AI-enhanced audio editing and restoration software from CyberLink."),
# ── AI MUSIC CREATION ─────────────────────────────────────────────────────────
("Suno","https://suno.com","ai-music","AI music generator that creates full songs with lyrics from text prompts."),
("Udio","https://udio.com","ai-music","AI platform generating high-quality music across all genres from text descriptions."),
("BeatStars","https://beatstars.com","ai-music","Largest online beat marketplace where producers sell beats to artists."),
("Airbit","https://airbit.com","ai-music","Beat licensing marketplace connecting producers with artists and content creators."),
("Looperman","https://looperman.com","ai-music","Free loop and acapella library created by and for musicians."),
("Splice","https://splice.com","ai-music","Sample, loop, and sound pack subscription service used by top producers."),
("LANDR","https://landr.com","ai-music","AI-powered mastering, distribution, samples, and music collaboration tools."),
("Soundraw","https://soundraw.io","ai-music","AI music generator that creates royalty-free tracks customizable by mood and genre."),
("Boomy","https://boomy.com","ai-music","Create and release AI-generated music to streaming platforms instantly."),
("Mubert","https://mubert.com","ai-music","AI generative music platform for content creators and developers."),
("Beatport","https://beatport.com","ai-music","The world's largest DJ and electronic music download store."),
("Traktrain","https://traktrain.com","ai-music","Premium beat marketplace focused on exclusive and lease licensing."),
("SoundClick","https://soundclick.com","ai-music","Music social network and beat marketplace for independent artists."),
("Soundraw AI","https://soundraw.io","ai-music","AI music composition tool for generating background and mood music."),
("Loudly","https://loudly.com","ai-music","AI music generator with stems and customizable tracks for creators."),
("Aiva","https://aiva.ai","ai-music","AI music composition assistant for film, game, and commercial soundtracks."),
("Amper Music","https://ampermusic.com","ai-music","AI music creation tool for brands and content creators."),
("Jukedeck","https://jukedeck.com","ai-music","AI music generator for creating original soundtracks (now part of TikTok)."),
("Ecrett Music","https://ecrettmusic.com","ai-music","AI music composer for video creators needing royalty-free background music."),
("Melodrive","https://melodrive.com","ai-music","AI adaptive music engine for interactive media and games."),
("Moises App","https://moises.ai","ai-music","AI-powered app for separating stems, removing vocals, and changing tempo."),
("Lalal.ai","https://lalal.ai","ai-music","AI stem splitter for separating vocals, drums, bass, and instruments."),
("AudioStrip","https://audiostrip.co.uk","ai-music","Free AI vocal remover and instrument isolation tool."),
("Fadr","https://fadr.com","ai-music","AI stem splitter and remix tool for DJs and music creators."),
("Samplab","https://samplab.com","ai-music","AI-powered sample chopper and loop generator from audio files."),
("Musicfy","https://musicfy.lol","ai-music","AI voice cloning and cover generation tool for music creators."),
("Covers.ai","https://covers.ai","ai-music","AI tool for generating voice covers of popular songs."),
("Voicify AI","https://voicify.ai","ai-music","AI voice model platform for creating AI covers and vocal transformations."),
("Stableaudio","https://stableaudio.com","ai-music","Stability AI's text-to-audio music generation model."),
("Meta MusicGen","https://audiocraft.metademolab.com","ai-music","Meta's open-source AI music generation model for researchers."),
# ── MUSIC EDUCATION ───────────────────────────────────────────────────────────
("Berklee Online","https://online.berklee.edu","education","World-renowned music school offering online certificates and degrees."),
("Coursera Music","https://coursera.org/browse/arts-and-humanities/music","education","University-level music courses from Berklee, Yale, and other top schools."),
("MasterClass Music","https://masterclass.com/categories/music","education","Learn from legends like Timbaland, Alicia Keys, and Deadmau5."),
("Udemy Music Production","https://udemy.com/courses/music","education","Thousands of music production courses from beginner to advanced."),
("Soundfly","https://soundfly.com","education","Modern online music school with courses on production, songwriting, and business."),
("Point Blank Music School","https://pointblankmusicschool.com","education","Professional music school with campuses in London, LA, and online."),
("SAE Institute","https://sae.edu","education","Global audio engineering and music production school."),
("Icon Collective","https://iconcollective.edu","education","Music production school in Los Angeles with online courses."),
("DistroKid Help","https://support.distrokid.com","education","Official DistroKid knowledge base for distribution tips and best practices."),
("Music Industry How To","https://musicindustryhowto.com","education","Comprehensive music industry education blog covering all career aspects."),
("Music Gateway Blog","https://music-gateway.com/blog","education","Industry insights, artist advice, and music business education."),
("Hypebot","https://hypebot.com","education","Daily music industry news and analysis for artists and professionals."),
("Digital Music News","https://digitalmusicnews.com","education","Breaking news and analysis of the music streaming and tech industry."),
("Music Business Worldwide","https://musicbusinessworldwide.com","education","Industry news site covering the global music business."),
("CD Baby DIY Musician","https://diymusician.cdbaby.com","education","Free resource blog for independent artists on music careers."),
("Tunecore Blog","https://blog.tunecore.com","education","Music industry advice and distribution tips from TuneCore."),
("Musician on a Mission","https://musicianonamission.com","education","YouTube channel and blog teaching music production fundamentals."),
("In The Mix","https://inthemix.net","education","Music production tutorials and tips for producers of all levels."),
("Produce Like A Pro","https://producelikeapro.com","education","YouTube channel with professional mixing and recording tutorials."),
("Mike Monday","https://mikemonday.com","education","Music career coaching for independent artists and songwriters."),
("Tommy Darker","https://tommydarker.com","education","Music business strategy blog for modern independent artists."),
("Music Think Tank","https://musicthinktank.com","education","Community-driven music business blog with artist-submitted articles."),
("The Music Entrepreneur HQ","https://themusidentrepreneur.com","education","Practical advice for building a sustainable music career."),
("Artist Shortcut","https://artistshortcut.com","education","Training platform for artists learning to grow their fanbase online."),
("Music Marketing Manifesto","https://musicmarketingmanifesto.com","education","Online music marketing course for independent artists."),
("Hypeddit","https://hypeddit.com","education","SoundCloud promotion and music marketing growth tools."),
("Bandzoogle Blog","https://bandzoogle.com/blog","education","Artist website tips and music career advice from Bandzoogle."),
("Artist.Tools","https://artist.tools","education","Free tools and resources for independent music artists."),
("Ari's Take","https://aristake.com","education","Industry insider blog by Ari Herstand covering all aspects of the music career."),
("New Artist Model","https://newartistmodel.com","education","Music business courses focused on the modern independent artist model."),
# ── LICENSING & ROYALTIES ─────────────────────────────────────────────────────
("ASCAP","https://ascap.com","licensing","American music rights organization representing over 900,000 songwriter members."),
("BMI","https://bmi.com","licensing","Broadcast Music Inc. collecting performance royalties for 1.4M+ creators."),
("SESAC","https://sesac.com","licensing","Selective performing rights organization for songwriters and publishers."),
("SoundExchange","https://soundexchange.com","licensing","Collects digital performance royalties from satellite and internet radio."),
("Songtrust","https://songtrust.com","licensing","Global publishing administration collecting royalties in 245+ countries."),
("Music Reports","https://musicreports.com","licensing","Music licensing and royalty reporting for digital music services."),
("Harry Fox Agency","https://harryfox.com","licensing","Mechanical licensing agency for reproducing musical compositions."),
("Songfile","https://songfile.com","licensing","Online mechanical license service for recording cover songs."),
("DistroKid Covers","https://distrokid.com/cover","licensing","Easy cover song licensing through DistroKid for streaming releases."),
("Easy Song","https://easysong.com","licensing","Online service for obtaining mechanical licenses for cover songs."),
("Cosynd","https://cosynd.com","licensing","Automated music contract and collaboration agreement platform."),
("TuneRegistry","https://tuneregistry.com","licensing","Music metadata and rights management for publishers and songwriters."),
("Lyric Find","https://lyricfind.com","licensing","Licensed lyrics provider for streaming platforms and music apps."),
("Music Bed","https://musicbed.com","licensing","High-quality sync music licensing for filmmakers and content creators."),
("Artlist","https://artlist.io","licensing","Music and SFX subscription for video creators with global sync license."),
("Epidemic Sound","https://epidemicsound.com","licensing","Royalty-free music subscription for YouTubers and content creators."),
("Soundstripe","https://soundstripe.com","licensing","Subscription sync license library for video, podcast, and social media."),
("Musicbed","https://musicbed.com","licensing","Premium sync licensing for professional filmmakers and brands."),
("Pond5","https://pond5.com/music","licensing","Stock music, SFX, and video asset marketplace for content creators."),
("Audiojungle","https://audiojungle.net","licensing","Envato's music licensing marketplace for royalty-free tracks."),
("PremiumBeat","https://premiumbeat.com","licensing","Shutterstock's curated royalty-free music library for filmmakers."),
("Marmoset","https://marmosetmusic.com","licensing","Curated sync music agency connecting artists with brands and films."),
("Musicube","https://musicube.com","licensing","AI-powered music metadata and sync licensing technology."),
("Soundsnap","https://soundsnap.com","licensing","Professional sound effects and music library for media production."),
("Jamendo","https://jamendo.com","licensing","Free music streaming and commercial music licensing platform."),
("Free Music Archive","https://freemusicarchive.org","licensing","Curated library of high-quality free and legal audio downloads."),
("ccMixter","https://ccmixter.org","licensing","Community music site featuring Creative Commons licensed remixes."),
("Incompetech","https://incompetech.com","licensing","Kevin MacLeod's library of free-to-use royalty-free music."),
("Bensound","https://bensound.com","licensing","Royalty-free music library for multimedia projects and content creators."),
("YouTube Audio Library","https://studio.youtube.com/channel/music","licensing","YouTube's free music and sound effects library for creators."),
# ── PROMOTION & PLAYLIST PITCHING ────────────────────────────────────────────
("SubmitHub","https://submithub.com","promotion","Blog, playlist, and radio submission platform with blogger feedback."),
("Groover","https://groover.co","promotion","Music promotion platform connecting artists with curators and media."),
("Playlist Push","https://playlistpush.com","promotion","Premium playlist promotion service with vetted Spotify curators."),
("Omari MC","https://omarimc.com","promotion","Music marketing services including Spotify playlists and YouTube promotion."),
("Soundcharts","https://soundcharts.com","promotion","Music analytics platform tracking streaming, charts, and audience data."),
("Chartmetric","https://chartmetric.com","promotion","Music analytics platform tracking artist growth across all platforms."),
("Submitmyhiphop","https://submitmyhiphop.com","promotion","Hip-hop specific blog and playlist submission platform."),
("Indie Music Academy","https://indiemusicacademy.com","promotion","Playlist promotion and Spotify growth service for independent artists."),
("Promoly","https://promoly.com","promotion","Music promotion platform for sending tracks to radio, blogs, and playlists."),
("ShowFour","https://showfour.io","promotion","Music marketing and playlist pitching tool for independent artists."),
("Pitch.Link","https://pitch.link","promotion","Direct music pitching tool for connecting with curators and blogs."),
("Indiemono","https://indiemono.com","promotion","Independent music promotion and submission site for emerging artists."),
("Musosoup","https://musosoup.com","promotion","Ethical music promotion platform connecting artists with bloggers."),
("CoverageAgent","https://coverageagent.com","promotion","Music PR and media coverage services for independent releases."),
("YouGrow","https://yougrow.io","promotion","Spotify promotion and artist growth service for independent releases."),
("Beatween","https://beatween.com","promotion","Music discovery and playlist pitch platform for independent artists."),
("Music Vine","https://musicvine.com","promotion","Artist submission platform for sync licensing and music discovery."),
("Musictogo","https://musictogo.net","promotion","Music promotion and directory submission service for indie artists."),
("Boost Collective","https://boostcollective.ca","promotion","Music promotion and Spotify playlist pitching for independent artists."),
("Freddie's Plug","https://freddieplug.com","promotion","Music marketing agency specializing in hip-hop and R&B promotions."),
("Music Xray","https://musicxray.com","promotion","Music submission platform connecting artists with industry professionals."),
("ReverbNation Opportunities","https://reverbnation.com/opportunities","promotion","Audition and opportunity submissions for gigs, labels, and sync."),
("The Unsigned Guide","https://theunsignedguide.com","promotion","Music industry directory with promotional opportunities for unsigned acts."),
("Cyber PR","https://cyberprmusic.com","promotion","Music PR and social media marketing for independent artists."),
("Right Chord Music","https://rightchordmusic.com","promotion","UK-based music blog accepting submissions from independent artists."),
("MySphera","https://mysphera.com","promotion","Music analytics and audience targeting for artist marketing campaigns."),
("Warm Cider","https://warmcider.com","promotion","Artist PR and radio promotion services for independent releases."),
("Indie on the Move","https://indieonthemove.com","promotion","Touring database and booking resource for independent musicians."),
("Jango","https://jango.com","promotion","Internet radio platform with artist promotion and listener targeting."),
("MusicSubmit","https://musicsubmit.com","promotion","Music submission service sending releases to radio, blogs, and playlists."),
# ── ARTIST WEBSITES & EPK ────────────────────────────────────────────────────
("Bandzoogle","https://bandzoogle.com","website","Purpose-built website platform for musicians with EPK, store, and booking tools."),
("Squarespace","https://squarespace.com","website","Popular website builder with beautiful templates suited for artists."),
("Wix","https://wix.com","website","Flexible website builder with music player, store, and EPK capabilities."),
("Sonicbids","https://sonicbids.com","website","EPK platform connecting bands with venues, festivals, and opportunities."),
("Music Glue","https://musicglue.com","website","Artist website, ticketing, and merchandise platform for musicians."),
("Flavors.me","https://flavors.me","website","Simple personal website builder aggregating social media profiles."),
("WordPress.com","https://wordpress.com","website","Popular blogging and website platform with music-specific themes."),
("Webflow","https://webflow.com","website","Professional no-code website builder for artists wanting custom designs."),
("Cargo","https://cargo.site","website","Minimalist portfolio and website platform popular with creative artists."),
("Format","https://format.com","website","Portfolio website platform for photographers and musicians."),
("Presskit.to","https://presskit.to","website","Simple online press kit creation tool for musicians and artists."),
("Linktree","https://linktr.ee","website","Bio link tool for sharing all your music links from one URL."),
("Beacons","https://beacons.ai","website","Creator link-in-bio tool with store, email list, and analytics features."),
("Koji","https://koji.to","website","App-based bio link platform with fan engagement monetization tools."),
("Shorby","https://shorby.com","website","Smart link and bio page tool for musicians and content creators."),
("Toneden","https://toneden.io","website","Music marketing and fan link tools for releasing and promoting music."),
("Feature.fm","https://feature.fm","website","Smart links and pre-save tools for music marketing campaigns."),
("Show.co","https://show.co","website","Music marketing platform with pre-save, smart links, and fan tools."),
("Hypeddit","https://hypeddit.com","website","SoundCloud promotion and smart link tool for artists."),
("Fanlink","https://fanlink.to","website","Music landing page and smart link builder for release campaigns."),
("Songwhip","https://songwhip.com","website","Automatic music link aggregator for sharing across all platforms."),
("Odesli","https://odesli.co","website","Smart music link tool connecting fans to their preferred streaming service."),
("Amuse Music","https://amuse.io","website","Mobile app and platform for creating artist profiles and distributing music."),
("Soundcloud","https://soundcloud.com","website","Audio streaming platform for sharing and discovering independent music."),
("Audiomack","https://audiomack.com","website","Free music streaming platform focused on hip-hop and emerging artists."),
("Bandsintown","https://bandsintown.com","website","Concert discovery and artist tracking platform for tour promotion."),
("Songkick","https://songkick.com","website","Concert and tour promotion platform connecting artists with fans."),
("Eventbrite Music","https://eventbrite.com/b/local/music","website","Event ticketing platform used by independent artists for shows."),
("Google My Business for Artists","https://business.google.com","website","Free business listing for artists appearing in local Google searches."),
# ── EQUIPMENT & GEAR ──────────────────────────────────────────────────────────
("Sweetwater","https://sweetwater.com","equipment","America's largest online music equipment retailer with expert sales staff."),
("Guitar Center","https://guitarcenter.com","equipment","Largest chain of musical instrument and equipment retailers in the US."),
("Musician's Friend","https://musiciansfriend.com","equipment","Online music gear retailer with a wide selection of instruments and equipment."),
("B&H Photo Audio","https://bhphotovideo.com","equipment","Professional camera, audio, and music equipment retailer in NYC."),
("American Musical Supply","https://americanmusical.com","equipment","Online music equipment retailer with no-interest financing options."),
("zZounds","https://zzounds.com","equipment","Online music equipment store specializing in payment plan options."),
("Reverb.com","https://reverb.com","equipment","Peer-to-peer marketplace for buying and selling new and used music gear."),
("eBay Musical Instruments","https://ebay.com/b/Musical-Instruments","equipment","Massive marketplace for new and vintage musical instruments and gear."),
("GearSpace","https://gearspace.com","equipment","Professional audio forums and reviews for recording equipment."),
("Thomann","https://thomann.de","equipment","Europe's largest music equipment retailer with worldwide shipping."),
("Sam Ash Music","https://samashmusic.com","equipment","Long-running musical instrument chain with online and physical stores."),
("MOOG","https://moogmusic.com","equipment","Iconic synthesizer manufacturer making handcrafted analog instruments."),
("Roland","https://roland.com","equipment","Japanese music equipment company making synthesizers, drum machines, and effects."),
("Native Instruments","https://native-instruments.com","equipment","Industry-leading software instruments, DAW controllers, and sample packs."),
("Arturia","https://arturia.com","equipment","French company making analog-modeled synthesizers and MIDI controllers."),
("Focusrite","https://focusrite.com","equipment","Leading audio interface manufacturer for home and professional studios."),
("Universal Audio","https://uaudio.com","equipment","Premium audio interfaces and analog-modeled plugins for recording."),
("Shure","https://shure.com","equipment","Professional microphone and audio electronics manufacturer."),
("Sennheiser","https://sennheiser.com","equipment","German audio company making professional microphones and headphones."),
("Audio-Technica","https://audio-technica.com","equipment","Professional microphones, headphones, and turntables for audio production."),
("Rode Microphones","https://rode.com","equipment","Australian microphone brand popular for podcast and studio recording."),
("Pioneer DJ","https://pioneerdj.com","equipment","Leading DJ equipment manufacturer making CDJs, mixers, and controllers."),
("Denon DJ","https://denondj.com","equipment","Professional DJ controllers and media players for live performance."),
("Rane DJ","https://ranedj.com","equipment","Premium DJ mixers and battle tools for DJs and turntablists."),
("Serato","https://serato.com","equipment","Industry-standard DJ software used by professional DJs worldwide."),
("Traktor","https://native-instruments.com/traktor","equipment","Native Instruments' professional DJ software and hardware ecosystem."),
("Ableton Push","https://ableton.com/push","equipment","Hardware controller designed for Ableton Live performance and production."),
("Maschine","https://native-instruments.com/maschine","equipment","NI's groove production studio combining hardware and software."),
("Akai MPC","https://akaipro.com","equipment","Iconic beat production hardware used by hip-hop producers worldwide."),
("Output","https://output.com","equipment","Innovative music production software and hardware for modern producers."),
# ── FUNDING & CROWDFUNDING ────────────────────────────────────────────────────
("Kickstarter Music","https://kickstarter.com/music","funding","Crowdfunding platform for financing album recordings, tours, and music projects."),
("Indiegogo Music","https://indiegogo.com","funding","Flexible crowdfunding platform used by artists for music and touring projects."),
("Patreon","https://patreon.com","funding","Membership platform for artists to receive recurring support from fans."),
("Ko-fi","https://ko-fi.com","funding","Simple tipping and membership platform for creators."),
("GoFundMe","https://gofundme.com","funding","Crowdfunding platform used by artists for personal and music projects."),
("Bandcamp Supporter","https://bandcamp.com","funding","Bandcamp's direct fan support system for album purchases and subscriptions."),
("Buy Me A Coffee","https://buymeacoffee.com","funding","Creator tipping platform for artists to receive direct fan support."),
("Drip","https://d.rip","funding","Patreon-style membership and crowdfunding platform for musicians."),
("Ampled","https://ampled.com","funding","Artist-owned cooperative platform for fan subscriptions and support."),
("Songkick Tickets","https://songkick.com","funding","Direct ticketing for artists to sell concert tickets directly to fans."),
("Feature.fm Pre-save","https://feature.fm","funding","Pre-save and fan funding tools for music releases and campaigns."),
("iFundWomen","https://ifundwomen.com","funding","Crowdfunding platform specifically supporting women-led creative businesses."),
("FundMyShow","https://fundmyshow.com","funding","Crowdfunding platform for artists to fund tours and live shows."),
("PledgeMusic","https://pledgemusic.com","funding","Fan-funded music project platform for pre-ordering and exclusive content."),
("NIVA Emergency Fund","https://nivafund.org","funding","National Independent Venue Association funding for music industry workers."),
("RIAA Foundation","https://riaa.com","funding","Music industry research and charity supporting the creator community."),
("Sweet Relief","https://sweetrelief.org","funding","Charity providing financial assistance to musicians facing hardship."),
("MusiCares","https://grammy.com/musicares","funding","Grammy Foundation charity providing health and financial help to music people."),
("Artists' General Welfare Fund","https://agwf.org","funding","Emergency financial assistance for professional performing artists."),
("Volunteer Lawyers for Arts","https://vlany.org","funding","Legal and financial resources for artists and arts organizations."),
# ── LEGAL & BUSINESS ──────────────────────────────────────────────────────────
("Entertainment Law Initiative","https://grammy.com/recording-academy/entertainment-law-initiative","legal","GRAMMY program connecting students with entertainment law professionals."),
("Artists House Music","https://artistshousemusic.org","legal","Non-profit providing music business education and mentorship."),
("TAXI","https://taxi.com","legal","Independent A&R company connecting artists with music industry opportunities."),
("Music Law 101","https://musiclaw101.com","legal","Educational resource for understanding music contracts and rights."),
("Cosynd","https://cosynd.com","legal","Platform for creating legally binding music collaboration agreements."),
("Songfile","https://songfile.com","legal","Harry Fox Agency's mechanical license portal for cover song recordings."),
("NOLO Music Law","https://nolo.com/legal-encyclopedia/music-law","legal","Plain-English legal guides covering music contracts and copyright."),
("Copyright.gov","https://copyright.gov","legal","US Copyright Office for registering songs and compositions."),
("USPTO","https://uspto.gov","legal","US Patent and Trademark Office for registering artist names and logos."),
("Music Law Advisor","https://musiclawadvisor.com","legal","Online resource for musicians navigating entertainment law."),
("Future of Music Coalition","https://futureofmusic.org","legal","Artist advocacy organization covering policy, rights, and revenue."),
("American Federation of Musicians","https://afm.org","legal","US musicians union providing contracts, advocacy, and benefits."),
("SAG-AFTRA","https://sagaftra.org","legal","Union representing recording artists and voice actors."),
("NARAS","https://grammy.com","legal","Recording Academy representing the interests of recording artists."),
("Broadcast Music Inc","https://bmi.com","legal","Performing rights organization for songwriters and publishers."),
("Songtrust PRO","https://songtrust.com","legal","Global publishing administration collecting mechanical and performance royalties."),
("LegalZoom Music","https://legalzoom.com","legal","Online legal services for forming music LLCs and filing copyrights."),
("Rocket Lawyer","https://rocketlawyer.com","legal","Online legal platform for creating music contracts and agreements."),
("Entertainment Law Resources","https://entertainment.law","legal","Legal database and directory for entertainment attorneys."),
("Artists Rights Alliance","https://artistrightsalliance.org","legal","Advocacy organization protecting the rights of music artists."),
# ── STREAMING & DISCOVERY ────────────────────────────────────────────────────
("Spotify for Artists","https://artists.spotify.com","streaming","Spotify's artist dashboard for managing profiles, pitching, and analytics."),
("Apple Music for Artists","https://artists.apple.com","streaming","Apple's analytics and profile management portal for musicians."),
("YouTube Studio","https://studio.youtube.com","streaming","YouTube's creator dashboard for managing music videos and analytics."),
("Amazon Music for Artists","https://artists.amazonmusic.com","streaming","Amazon Music's artist portal for profile management and analytics."),
("Tidal for Artists","https://tidal.com/artist","streaming","TIDAL's artist services with high-fidelity audio and fan connections."),
("Deezer for Artists","https://deezerartists.com","streaming","Deezer's artist portal for managing profiles and tracking streams."),
("Audiomack","https://audiomack.com","streaming","Free music streaming platform especially popular for hip-hop and Afrobeats."),
("SoundCloud for Artists","https://soundcloud.com/for-creators","streaming","Artist tools for SoundCloud including monetization and analytics."),
("Pandora AMP","https://amp.pandora.com","streaming","Pandora's artist marketing platform for reaching their radio audience."),
("iHeartRadio","https://iheartradio.com","streaming","Major internet radio platform with artist submission capabilities."),
("Napster","https://napster.com","streaming","Music streaming service with artist revenue sharing for superfans."),
("Qobuz","https://qobuz.com","streaming","Hi-res audio streaming service for audiophiles with artist royalties."),
("Bandcamp","https://bandcamp.com","streaming","Direct-to-fan platform keeping 85% for artists on sales and streams."),
("Reverb Nation","https://reverbnation.com","streaming","Artist promotion hub with streaming, EPK, and opportunity tools."),
("Anghami","https://anghami.com","streaming","Leading streaming platform across the Arab World for regional reach."),
("JioSaavn","https://jiosaavn.com","streaming","India's largest music streaming platform for reaching South Asian audiences."),
("Boomplay","https://boomplaymusic.com","streaming","Africa's most popular music streaming app for reaching African audiences."),
("Gaana","https://gaana.com","streaming","India's #1 music streaming app with 200M+ monthly users."),
("NetEase Cloud Music","https://music.163.com","streaming","China's top music streaming platform for reaching Asian audiences."),
("Melon","https://melon.com","streaming","South Korea's most popular music streaming service."),
("Bugs Music","https://music.bugs.co.kr","streaming","Korean music platform for accessing the South Korean music market."),
("Line Music","https://music.line.me","streaming","Japan-focused music streaming service for the Asian market."),
("Resso","https://resso.com","streaming","ByteDance's social music streaming app popular in emerging markets."),
("Mixcloud","https://mixcloud.com","streaming","DJ mix and radio show streaming platform with royalty payments."),
("Hearthis.at","https://hearthis.at","streaming","European music streaming platform for DJs and electronic artists."),
("Jamendo","https://jamendo.com","streaming","Free music streaming with commercial licensing for independent artists."),
("DistroKid HyperFollow","https://distrokid.com/hyperfollow","streaming","DistroKid's pre-save and release landing page tool."),
("Spotify Canvas","https://artists.spotify.com/guide/canvas","streaming","Spotify's looping video feature for artist track pages."),
("Apple Music Connect","https://apple.com/music","streaming","Apple Music's artist content sharing tool for fan engagement."),
("YouTube Music","https://music.youtube.com","streaming","Google's music streaming service integrated with YouTube."),
# ── SOCIAL & COMMUNITY ────────────────────────────────────────────────────────
("TikTok for Music","https://tiktokforbusiness.com/music","social","TikTok's music marketing tools reaching 1B+ users through short video."),
("Instagram for Creators","https://creators.instagram.com","social","Instagram's creator tools for music promotion through Reels and Stories."),
("Twitter/X Music","https://music.twitter.com","social","Music discovery and sharing features integrated into Twitter/X."),
("Facebook for Artists","https://facebook.com/music","social","Facebook's music tools including live audio rooms and fan subscriptions."),
("Discord Music Communities","https://discord.com","social","Text and voice communities for artists to build dedicated fan bases."),
("r/WeAreTheMusicMakers","https://reddit.com/r/WeAreTheMusicMakers","social","Reddit's largest community for music producers sharing knowledge."),
("r/WeAreTheMusicMakers Discord","https://discord.gg/watmm","social","Official Discord community for the WeAreTheMusicMakers subreddit."),
("Clubhouse Music","https://joinclubhouse.com","social","Drop-in audio app used by musicians for live performances and talks."),
("StageIt","https://stageit.com","social","Live ticketed performance platform for artists to monetize virtual shows."),
("Twitch Music","https://twitch.tv/music","social","Live streaming platform for musicians to perform and engage fans."),
("Triller","https://triller.co","social","Short-form video platform competing with TikTok focused on music."),
("Byte","https://byte.co","social","Short video platform by the creator of Vine for musicians."),
("Audiusio","https://audius.co","social","Decentralized music streaming platform built on blockchain."),
("Stem Disintermedia","https://stem.is","social","Music payment and analytics platform for modern artists."),
("Bandsintown Fan Manager","https://managers.bandsintown.com","social","Tools for artists to engage fans and promote shows through Bandsintown."),
("Songkick Tourbox","https://tourbox.songkick.com","social","Tool for artists to manage tour dates and sync with Songkick."),
("LinkedIn for Musicians","https://linkedin.com","social","Professional networking for music industry connections and B2B relationships."),
("Wavo","https://wavo.me","social","Smart link and social media posting tool for music releases."),
("Mailchimp for Musicians","https://mailchimp.com","social","Email marketing platform used by artists for newsletters and fan updates."),
("ConvertKit","https://convertkit.com","social","Email marketing platform popular among independent artists for fan lists."),
("Substack Music","https://substack.com","social","Newsletter platform for artists publishing content directly to fans."),
("Patreon Community","https://patreon.com","social","Fan membership and community platform for exclusive artist content."),
("OnlyFans Music","https://onlyfans.com","social","Subscription content platform used by some artists for exclusive releases."),
("Cameo","https://cameo.com","social","Platform for celebrities and artists to sell personalized video messages."),
("Fanbase","https://fanbase.app","social","Black-owned social media platform for creators with built-in monetization."),
("Superpeer","https://superpeer.com","social","Video call and content platform for creators charging for 1-on-1 access."),
("Stir","https://stirlabs.com","social","Creator collaboration and business management platform."),
("Counterpoint","https://counterpoint.app","social","Community platform for musicians to connect and collaborate."),
# ── MUSIC INDUSTRY NEWS ────────────────────────────────────────────────────────
("Billboard","https://billboard.com","industry","The most authoritative music charts and industry news publication."),
("Rolling Stone","https://rollingstone.com","industry","Iconic music magazine covering pop culture, politics, and the music industry."),
("Pitchfork","https://pitchfork.com","industry","Influential music review site known for indie and alternative coverage."),
("Variety Music","https://variety.com/v/music","industry","Entertainment trade publication covering the music business."),
("The Hollywood Reporter Music","https://hollywoodreporter.com/music","industry","Industry trade covering music from Hollywood's perspective."),
("NME","https://nme.com","industry","UK-based music magazine covering rock, pop, and indie news."),
("AllHipHop","https://allhiphop.com","industry","Premier hip-hop news, interviews, and music coverage website."),
("XXL Magazine","https://xxlmag.com","industry","Hip-hop culture magazine known for its annual Freshman Class issue."),
("The Source","https://thesource.com","industry","Original hip-hop magazine with news, reviews, and culture coverage."),
("Consequence of Sound","https://consequence.net","industry","Independent music news, reviews, and concert coverage."),
("Stereogum","https://stereogum.com","industry","Indie music blog with reviews, news, and MP3 premieres."),
("The FADER","https://thefader.com","industry","Music and culture magazine focused on cutting-edge artists."),
("Complex Music","https://complex.com/music","industry","Hip-hop and streetwear culture hub with music news and artist interviews."),
("Rated R&B","https://ratedrb.com","industry","R&B focused music news, reviews, and industry coverage."),
("Ones To Watch","https://ones2watch.com","industry","Music discovery platform highlighting breaking artists."),
("Lyrical Lemonade","https://lyricallemonade.com","industry","Gen-Z music media brand known for YouTube visuals and hip-hop coverage."),
("The Root Music","https://theroot.com/entertainment/music","industry","Black culture publication covering music from an African American lens."),
("Exclaim!","https://exclaim.ca","industry","Canada's largest independent music media brand."),
("Clash Magazine","https://clashmusic.com","industry","UK music magazine covering indie, alternative, and electronic music."),
("Flood Magazine","https://floodmagazine.com","industry","Music discovery publication highlighting emerging artists globally."),
("Resident Advisor","https://ra.co","industry","Electronic music magazine and event guide for global dance culture."),
("Magnetic Magazine","https://magneticmag.com","industry","Electronic dance music news and artist coverage."),
("Your EDM","https://youredm.com","industry","EDM news, reviews, and culture for electronic music fans."),
("Dancing Astronaut","https://dancingastronaut.com","industry","Electronic music media brand covering festivals and producers."),
("Earmilk","https://earmilk.com","industry","Music discovery platform featuring independent and emerging artists."),
("Impose Magazine","https://imposemagazine.com","industry","Independent music and culture magazine with artist features."),
("Midnight Magazine","https://midnight-mag.com","industry","Hip-hop and R&B music magazine featuring emerging artists."),
("Songwriting Magazine","https://songwritingmagazine.co.uk","industry","UK publication dedicated to the craft and business of songwriting."),
("Guitar World","https://guitarworld.com","industry","Leading guitar magazine with lessons, gear reviews, and artist interviews."),
("Tape Op","https://tapeop.com","industry","Free music recording magazine for home and professional studios."),
# ── SAMPLE PACKS & LOOPS ──────────────────────────────────────────────────────
("Loopmasters","https://loopmasters.com","samples","Premium sample pack store with thousands of packs across all genres."),
("Sample Magic","https://samplemagic.com","samples","Professional sample packs and music production courses."),
("Capsule","https://capsulesamples.com","samples","Independent sample pack label focused on quality genre-specific packs."),
("Output Arcade","https://output.com/arcade","samples","Loop-based synthesizer with continuously updated creative sample content."),
("Spitfire Audio","https://spitfireaudio.com","samples","Industry-leading orchestral and cinematic sample libraries."),
("EastWest Sounds","https://soundsonline.com","samples","Professional orchestral and instrument sample library for composers."),
("Native Instruments Komplete","https://native-instruments.com/komplete","samples","Comprehensive bundle of virtual instruments, effects, and samples."),
("Roland Cloud","https://roland.com/roland-cloud","samples","Cloud subscription for Roland's iconic drum machine and synth sounds."),
("Goldbaby","https://goldbaby.co.nz","samples","Vintage and rare sampled drum machines and instruments."),
("Sounds.com","https://sounds.com","samples","Roland-owned sample marketplace with subscription access."),
("Wave Alchemy","https://wavealchemy.co.uk","samples","UK sample label making professional packs for electronic music producers."),
("Producer Loops","https://producerloops.com","samples","Large sample pack store with a wide variety of genres."),
("Big Fish Audio","https://bigfishaudio.com","samples","Professional sample library company with thousands of products."),
("Zero-G","https://zerog.co.uk","samples","UK-based sample library company with a wide range of genres."),
("Platinumloops","https://platinumloops.com","samples","Free and premium sample loops for music producers."),
("ADSR Sounds","https://adsrsounds.com","samples","Sample pack marketplace and synth preset store."),
("Prime Loops","https://primeloops.com","samples","Professional sample packs focused on urban and electronic music."),
("Beatport Sounds","https://sounds.beatport.com","samples","Sample packs curated for DJs and electronic music producers."),
("Loopazon","https://loopazon.com","samples","Free sample pack aggregator collecting freebies from across the web."),
("Musical Sampling","https://musicalsampling.com","samples","Cinematic and orchestral sample libraries for film composers."),
("Strezov Sampling","https://strezov.com","samples","Boutique orchestral sample library company from Bulgaria."),
("Impact Soundworks","https://impactsoundworks.com","samples","Innovative sample library developer known for ethnic and hybrid sounds."),
("8Dio","https://8dio.com","samples","Cinematic sample library with a wide range of orchestral content."),
("ProjectSAM","https://projectsam.com","samples","Cinematic sample library developer for film and TV scoring."),
("Heavyocity","https://heavyocity.com","samples","Cinematic production tools for film, TV, and game composers."),
("Output Portal","https://output.com/products/portal","samples","Granular synthesis plugin for creative sound design."),
("Capsaicin","https://capsaicinsound.com","samples","Experimental and creative sample packs for adventurous producers."),
("The Hit Kit","https://thehitkit.com","samples","Sample packs used by chart-topping producers and hit songwriters."),
("Cymatics","https://cymatics.fm","samples","High-quality free and premium sample packs for trap and EDM producers."),
("Ghosthack","https://ghosthack.de","samples","Free and premium sample packs for electronic music producers."),
# ── MANAGEMENT & BUSINESS TOOLS ──────────────────────────────────────────────
("Simmonds & Narita","https://snlegalmgmt.com","management","Music business management firm for independent artist financial planning."),
("Sonicbids EPK","https://sonicbids.com","management","Electronic press kit and booking platform for independent musicians."),
("Indie Artist Resource","https://indieartistresource.com","management","Business tools and education for independent music professionals."),
("Music Ally","https://musically.com","management","Music industry research, training, and strategy consulting."),
("Synchtank","https://synchtank.com","management","Rights management and licensing workflow software for publishers."),
("DISCO","https://disco.ac","management","Cloud-based music delivery and metadata platform for professionals."),
("Reprtoir","https://reprtoir.com","management","Music publishing catalog management software for indie publishers."),
("Curve Royalty Systems","https://curveroyalty.com","management","Royalty accounting and payment platform for music companies."),
("Royalty Exchange","https://royaltyexchange.com","management","Marketplace for buying and selling music royalties as investments."),
("Music Reports","https://musicreports.com","management","Licensing data management and royalty reporting services."),
("Exactly Right Media","https://exactlyrightmedia.com","management","Podcast and music media management consultancy."),
("Dashgo","https://dashgo.com","management","Channel management and revenue optimization for music YouTube channels."),
("Stem","https://stem.is","management","Artist payment splitting and analytics platform for modern releases."),
("Workman Entertainment","https://workmanent.com","management","Artist management services for independent acts."),
("Music Publisher","https://musicpublisher.com","management","Software for indie publishers to manage catalogs and royalties."),
("MusicHub","https://musichub.io","management","Artist management and music business platform for professionals."),
("Bandzoogle Pro","https://bandzoogle.com/pro","management","Professional artist website with EPK, store, and booking management."),
("ArtistGrowth","https://artistgrowth.com","management","Tour and business management software for artists and managers."),
("Gigmor","https://gigmor.com","management","Booking platform connecting venues with independent musicians for gigs."),
("Indie on the Move","https://indieonthemove.com","management","Touring resource database with venue contacts for independent artists."),
("RouteNote Reporting","https://routenote.com/reporting","management","Detailed streaming analytics and royalty reports for RouteNote artists."),
("Amuse Backstage","https://amuse.io/backstage","management","Analytics and royalty management dashboard for Amuse artists."),
("TuneCore Insights","https://tunecore.com/insights","management","Streaming analytics and fan data for TuneCore artists."),
("DistroKid Stats","https://distrokid.com/stats","management","Real-time streaming stats and earnings dashboard for DistroKid users."),
("Chartmetric Pro","https://chartmetric.com","management","Professional music analytics for tracking artist growth and streaming trends."),
("Soundcharts Pro","https://soundcharts.com","management","Music analytics platform used by labels, managers, and publishers."),
("Viberate","https://viberate.com","management","Music analytics and A&R discovery platform for industry professionals."),
("Next Big Sound","https://nextbigsound.com","management","Pandora-owned music analytics platform for tracking artist data."),
("MusicMetric","https://musicmetric.com","management","Artist data analytics for understanding fan demographics and behavior."),
("Groover Backstage","https://groover.co/backstage","management","Analytics dashboard for music promotion campaigns on Groover."),
# ── ARTISPRENEUR-SPECIFIC RESOURCES ──────────────────────────────────────────
("Artispreneur","https://artispreneur.com","artispreneur","The original Artispreneur platform connecting artists with resources and contacts."),
("Artispreneur Directory","https://directory.artispreneur.com","artispreneur","Comprehensive music industry database of 78,000+ verified contacts."),
("Artispreneur Academy","https://academy.artispreneur.com","artispreneur","Artispreneur's education platform with courses for independent artists."),
("Artispreneur Agent","https://agent.artispreneur.com","artispreneur","AI-powered music industry agent built on the Artispreneur platform."),
("Artispreneur OS","https://os.artispreneur.com","artispreneur","Artispreneur's operating system for managing your music business."),
("Music Industry Bible","https://artispreneur.com/bible","artispreneur","Artispreneur's free guide to every aspect of the music industry."),
("Submit to Artispreneur","https://artispreneur.com/submit","artispreneur","Submit your EPK to be featured in the Artispreneur database."),
]

def make_resource(name, website, subcategory, description):
    return {
        "id": str(uuid.uuid4()),
        "name": name,
        "type": "resource",
        "subcategory": subcategory,
        "location": "Global",
        "city": "",
        "state": "",
        "country": "Global",
        "description": description,
        "website": website,
        "email": "",
        "genre": "All Genres",
    }

records = [make_resource(name, website, subcat, desc) for name, website, subcat, desc in RAW]

# Deduplicate by name
seen = set()
unique = []
for r in records:
    if r["name"] not in seen:
        seen.add(r["name"])
        unique.append(r)

print(f"Total resources: {len(unique)}")

# Count by subcategory
from collections import Counter
counts = Counter(r["subcategory"] for r in unique)
for k, v in sorted(counts.items(), key=lambda x: -x[1]):
    print(f"  {k}: {v}")

out_path = os.path.join(OUT_DIR, "contacts_by_type", "resource.json")
with open(out_path, "w") as f:
    json.dump(unique, f, indent=2)
print(f"\nWritten: {out_path}")
print(f"Record count: {len(unique)}")
